### PR TITLE
Fixed ESRI maps not exporting

### LINKED ISSUE #24: Problem with Exporting Geotiff files when using ESRI maps
Hi there,
First, thank you for sharing this fantastic source code! 

I have encountered one problem when experimenting with the ESRI maps. If I load the ESRI basemap as a datalayer (as included in the original datasets.json script), everything works fine except the final step of exporting the output.  A error message of 'undefined' appears on the front-end when I click on the 'Download' button (see the screenshot). No error msg appears in the server.py though.  Also no problem with 'Download' if I use any other formats of datasets (e.g, type = 'CUSTOM' or 'USA_LAYER' or 'CVPR Landcover Layer.  Anyone knows how to resolve this ?   Many thanks!

image

### PR DESCRIPTION
**Pull request by Will747**
This PR fixes #24

Hi, as mentioned in the issue `get_data_from_geometry` was unimplemented so I implemented it based on the `get_data_from_extent` function and added an area restriction. Although I'm not sure if this would be best in the `get_data_from_geometry` function so it won't affect other DataLoaders and if 10km^2 is about the right max size.

### CODE REVIEW

**Comment by calebrob6** [comment]
Have you tested this locally?

**Comment by Will747** [comment]
Yes, both with more then 10km^2 and the ones lower successfully loaded
Screenshot 2022-06-09 183321
.

**Comment by calebrob6** [comment]
Cool! Thanks for the contribution :)

**Comment by Will747** [comment]
No problem, happy to of contributed

**Pull request merged**
